FROM node:lts as base

ARG _DATABASE_URL
ARG _DIRECT_URL
ENV DIRECT_URL $_DIRECT_URL
ENV DATABASE_URL $_DATABASE_URL


RUN curl -fsSL https://bun.sh/install | bash
WORKDIR /app

COPY . .

RUN ~/.bun/bin/bun install --production --frozen-lockfile
RUN ~/.bun/bin/bunx prisma generate --schema=./prisma/schema.prisma
RUN ~/.bun/bin/bunx prisma migrate deploy --schema=./prisma/schema.prisma

FROM oven/bun
COPY --from=base /app /app
WORKDIR /app
ENTRYPOINT ["bun",  "./src/index.ts"]