FROM oven/bun:latest

ENV APP_HOME /app

WORKDIR $APP_HOME

COPY . ./

RUN bun install --production --frozen-lockfile

RUN bunx prisma generate
RUN bunx prisma migrate deploy

ENTRYPOINT ["bun",  "./src/index.ts"]